garnet: hidl: Declare missing hals in FCM
The following HALs in device manifest are not declared in FCM <= level 6:
  android.hardware.biometrics.fingerprint.IFingerprint/default (@4)
  android.hardware.bluetooth.audio.IBluetoothAudioProviderFactory/default (@4)
  android.hardware.boot.IBootControl/default (@1)
  android.hardware.ir.IConsumerIr/default (@1)
  android.hardware.power.IPower/default (@4)
  android.hardware.sensors.ISensors/default (@2)
  android.hardware.usb.IUsb/default (@1)
  android.hardware.usb.gadget.IUsbGadget/default (@1)
  android.hardware.wifi.IWifi/default (@2)
  android.hardware.wifi.hostapd.IHostapd/default (@2)
  android.hardware.wifi.supplicant.ISupplicant/default (@3)
  vendor.dolby.hardware.dms@2.0::IDms/default
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.dolby.hardware.dms@2.0::IDms/default

Signed-off-by: Sensei <senseidev23@gmail.com>